server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 169167866Spl.
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # rabbitMQ配置
  rabbitmq:
    host: 192.168.0.175
    port: 5672
    virtual-host: /wangsen
    username: wangsen
    password: 123456


# 配置mybatis实体和xml映射
mybatis-plus:
  type-aliases-package: com.ws.*.entity.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 是否开启驼峰命名映射（若开启会自动将表中下划线命名的字段映射为类中驼峰命名的字段）
  mapper-locations: classpath*:com/ws/**/mapper/**/*.xml




# 配置日志级别
logging:
  level:
    org:
      springframework=DEBUG:
    com:
      ws=DEBUG:
